puppetlabs/puppetdb-cli

CMakeLists.txt, exe/CMakeLists.txt, exe/puppetdb-cli.cc, lib/CMakeLists.txt, lib/inc/puppetdb-cli/puppetdb-cli.hpp, lib/src/puppetdb-cli.cc, lib/tests/CMakeLists.txt, lib/tests/puppetdb-cli.cc
This commit removes the unused leatherman::curl dependency from the
project.
=> (PDB-2351) Remove dependency on leatherman::curl

exe/CMakeLists.txt, exe/puppet-db.cc, exe/puppet-query.cc
This commit separates out a puppet-query and puppet-db command from the
the current code by making two executables, one for querying PuppetDB
and another for administrative database tasks.
=> (PDB-2340) Separate out Puppet subcommands for db and query

README.md, exe/CMakeLists.txt, exe/puppet-db.cc, exe/puppet-query.cc, lib/CMakeLists.txt, lib/inc/puppetdb-cli/puppetdb-cli.hpp, lib/src/puppetdb-cli.cc, lib/tests/CMakeLists.txt, lib/tests/puppetdb-cli.cc
This commit removes a bug where the default configuration JSON was in
the incorrect format. This commit also adds the ability to pass in
either a single `server_urls` as a string or an array of `server_urls`
for PuppetDB failover. This commit catches JSON parse errors as well and
warns the user when they are encoutered, falling back to the default
configuration.
This commit also aligns the format of the CLI configuration file with
all of the other PuppetDB configuration files, such that there is now a
single `puppetdb` header where you specify your server_urls and ssl
credentials. We do lose the ability to specify multiple PuppetDB
environments but we'll gain this back we add in the ability to specify
the path to the config file via a command line flag.
=> (maint) Add better config file handling

exe/puppet-db.cc, lib/inc/puppetdb-cli/puppetdb-cli.hpp, lib/src/puppetdb-cli.cc
PDB imports no longer require a command_versions parameters and instead
parses the import tarball until it finds the metadata.
=> (maint) Remove command-versions flag from import

CMakeLists.txt, exe/puppet-db.cc, exe/puppet-query.cc, lib/inc/puppetdb-cli/puppetdb-cli.hpp, lib/src/puppetdb-cli.cc, man/puppet-db.pod, man/puppet-query.pod, man/puppetdb_conf.pod
This commit allows import and export arguments (specifically infile and
outfile respectively) to be supplied positionally to at the command
line. Whereas before a user would have needed to do
```
puppet-db import --infile foo
```
They may now do
```
puppet-db import foo
```
This PR also adds `--urls`, `--cacert/--cert/--key` flags to the global options for the CLI and now makes sure we parse `server_urls` when it's a string.
=> (PDB-2387) Add config flags for SSL auth

exe/puppet-query.cc
query is listed separately from <query> in the usages section of puppetdb-query help, it should just be <query>
=> (MAINT) Minor fixup to puppetdb-query help

exe/puppet-query.cc
Changed the CLI to fail when not given a query. This currently passes
empty string to PuppetDB which then fails with a query parse error. This
changes tells the user the query arg was missing and displays help.
=> (MAINT) Error when no query is supplied

CHANGELOG.md
This commit adds the initial release notes for the PuppetDB CLI's first
release.
=> (PDB-2549) Add initial CHANGELOG for the first release

Cargo.toml, src/lib.rs, src/net.rs
This commit adds the openssl-verify dependency to the puppetdb-cli which
adds support for verifying hostnames when connecting to PuppetDB over
HTTPS.
=> (maint) Verify hostnames with OpenSSL

man/puppet-db.pod, man/puppet-query.pod, man/puppetdb_conf.pod, pod2man.sh
This commit adds the logic for building our manpages using pod2man to
the Cargo build script.
=> (PDB-2763) Add man pages for Rust CLI

acceptance/setup/pe/pre_suite/00_setup_env.rb
This commit patches over RE-1990 (where our redhat repos are misnamed in
ezbake) by copying a patched beaker repo-installation utils function
from puppet-access.
=> (maint) Fix acceptance pre-suite for PE redhat testing

Cargo.toml, README.md, man/puppetdb_conf.pod, src/admin.rs, src/client.rs, src/config.rs, src/db.rs, src/lib.rs, src/net.rs, src/query.rs
This commit adds the ability to use a global configuration file with the
PuppetDB CLI, which we will fall back to if values in the per-user
config file are missing. This global config file is located at
`/etc/puppetlabs/client-tools/puppetdb.conf` similar to the location for
the global config for the other pe-client-tools.
=> (PDB-2815) Look for global configuration file

src/admin.rs, src/client.rs, src/db.rs, src/query.rs, src/utils.rs
Prior to this commit leatherman and std::env::home_dir() had different
ways of finding the home directory on Windows. This commit aligns our
C++ and Rust code by unsetting $HOME before using std::env::home_dir()
from Rust code.
=> (PDB-2856) Tidy up Windows support for the PuppetDB CLI

acceptance/setup/pe/pre_suite/00_setup_env.rb
This commit is a temporary measure which removes any previous PuppetDB
CLI configuration before running our acceptance tests.
=> (PDB-2957) Remove existing PuppetDB CLI configuration before tests

puppet_access/src/lib.rs
This commit fixes a bug (that currently only surfaces in Windows testing
but exists for all platforms) where tokens with extra whitespace in the
file will break the HTTP request made from the PuppetDB CLI.
=> (PDB-2957) Remove whitespace around tokens

Cargo.toml, src/client.rs, src/lib.rs, src/query.rs
Remove beautician dependency and pass pretty-printed output from the API
straight to stdout. This simplifies the code a bit and gets us around a
beautician bug that caused us to mishandle UTF8 in CLI results.
=> (PDB-2940) fix utf8 handling

pod2man.sh
Prior to this commit the manpages for the PuppetDB CLI were missing a
man8 from their install path. This commit ensures that the manpages are
installed to the correct location.
=> (PDB-2961) Install manpages to correct path

acceptance/Gemfile
This commit adds an acceptance testing Gemfile dependency on the beaker-abs gem,
which is necessary in order for the pipeline to run on CI.next.
----
We've had a successful run of the pipeline with this change, which can be seen here: https://jenkins-master-prod-1.delivery.puppetlabs.net/view/puppet-client-tools/
=> (QENG-4313) Add beaker-abs dependency for CI.next support

src/query.rs
This commit changes the `puppet-query` subcommand to display a nicer
error when it fails to write the response from a query, for example when
there is a BrokenPipe. Prior to this commit we were spitting a stack
trace with less meaningful output on BrokenPipe errors.
Before:
```
[maint/pull_utility_functions_to_shared_library][~/Projects/puppetdb-cli]$ ./target/debug/puppet-query 'nodes {}' | less
thread 'main' panicked at 'failed to write response', ../src/libcore/option.rs:705
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
After:
```
[maint/pull_utility_functions_to_shared_library][~/Projects/puppetdb-cli]$ ./target/debug/puppet-query 'nodes {}' | less
Failed to write response: Broken pipe (os error 32)
```
=> (PDB-3158) Use pretty_panic! for BrokenPipe errors

acceptance/Rakefile
This commit adds a `PE_FAMILY` environment variable to be used in
the creation of the `pe_dist_dir` and `pe_ver` values. The existing
default value for `pe_dist_dir` has been removed. This means that the
`PE_FAMILY` value must be set by the Jenkins job or the rake task will fail.
=> (PE-18967) Add PE_FAMILY env for acceptance tests

acceptance/Gemfile, acceptance/Rakefile
Prior to this commit, only the client test target was configurable when running
the acceptance tests. The master test target was hardcoded, and the vmpooler
hypervisor was always used by Beaker (by virtue of not specifying a hypervisor,
resulting the in the default vmpooler one).
In order to run in CI.next though, all test targets must be known ahead of time,
and the ABS hypervisor must be used by Beaker.
This commit allows for a pre-generated Beaker hosts file to be used, by
specifying it as the value of the BEAKER_HOSTS environment variable.
If BEAKER_HOSTS is not defined, the original behavior will be used.
=> (QENG-4283) Make Beaker hosts file configurable

Cargo.lock, Cargo.toml, acceptance/Gemfile, acceptance/Rakefile, appveyor.yml, src/client.rs, src/query.rs
This commit bumps all the core dependencies to their latest versions now
that multipart has updated it's dependency on hyper, this corresponds to
using hyper-openssl instead of openssl-verify (a now deprecated
library).
=> (maint) Update hyper, rust-openssl, and multipart dependencies

Cargo.lock, Cargo.toml
Version 1.2.1 was previously released reporting 1.3.0. The actual
changes were only bug fixes, so continuing in the 1.2 line with 1.2.2.
=> (maint) Update version to 1.2.2

pod2man.sh
Manpages generation was broken on FreeBSD.  These commits improve portability allowing the man page to build successfully on this platform.
=> (maint) Portability fixes

acceptance/Gemfile, acceptance/pe/setup/pre_suite/00_setup_env.rb
Move to Beaker 4 and bump acceptance testing gems for changes to the
Windows puppet-agent layout in Puppet 6.
=> (maint) Fix acceptance test setup

.rubocop.yml, README.md, lib/puppetdb_cli.rb, lib/puppetdb_cli/db.rb, lib/puppetdb_cli/query.rb, lib/puppetdb_cli/utils.rb, lib/puppetdb_cli/utils/default_options.rb, spec/spec_helper.rb, spec/unit/puppetdb_cli/db_spec.rb, spec/unit/puppetdb_cli/query_spec.rb, spec/unit/puppetdb_cli_spec.rb
Before they resided in the top level 'puppet' command, which created
confusing help output with the message "Options for Puppet" when the
options would never actually reach what end users would think of as the
puppet command.
They've now been added to the puppet-query and puppet-db commands
for more sane help output.
=> Move common arguments to query and db commands

acceptance/Rakefile
Now that we are using artifactory (and could change in the future), stop hard-coding BEAKER_PE_DIR and respect the environment variable so that this can be set in CI pipelines.
=> (maint) Stop hard-coding enterprise.d.p.n for beaker_pe_dir

.travis.yml
Newer versions of rust find some bad code in dependencies. This commit pins to older compiler versions we use to build and ship the rust components in pe-client-tools.
=> (maint) Pin rust to older versions

cmd/root.go
Fix an issue where puppetdb-cli does not honor token files provided in
the configuration files.
This happened because the token check was done prior to the config file
reading/merging.
=> (maint) Fix token loading

cmd/puppet-db/export.go, cmd/puppet-db/import.go, cmd/puppet-db/status.go, cmd/root.go
Our CLI also shows an usage message when we threw the `ssl requires a
token...` error. Silence the usage message so it behaves like its rust
counterpart.
=> (maint) Silence usage message on ArgError

acceptance/pe/tests/query_without_permissions.rb, api/api.yaml, api/client/operations/get_query_responses.go
In case of insufficient permissions of a user, a string
message is returned while puppet-query expect an error json.
Model was updated to handle string response for HTTP error 403.
=> (CT-133) handle HTTP error 403 returning string

api/swaggerclient.go
use default function https://golang.org/pkg/net/http/#ProxyFromEnvironment
for proxy environment variables handling
=> (CT-150) use proxy environment variables
